CREATE TABLE IF NOT EXISTS monsters (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    challenge_rating real NOT NULL,
    xp smallint NOT NULL,
    proficiency_bonus smallint NOT NULL,
    size size NOT NULL,
    monster_type monster_type NOT NULL,
    species text,
    alignment alignment NOT NULL,
    strength smallint NOT NULL,
    dexterity smallint NOT NULL,
    constitution smallint NOT NULL,
    intelligence smallint NOT NULL,
    wisdom smallint NOT NULL,
    charisma smallint NOT NULL,
    hit_points smallint NOT NULL,
    rollable_hit_points text NOT NULL,
    armor_class smallint NOT NULL,
    armor_type text,
    passive_perception smallint NOT NULL,
    available_legendary_actions smallint,
    bonus_actions jsonb NOT NULL DEFAULT '[]'::jsonb,
    condition_immunities condition[] NOT NULL DEFAULT '{}',
    damage_immunities damage_type[] NOT NULL DEFAULT '{}',
    damage_resistances damage_type[] NOT NULL DEFAULT '{}',
    lair_actions jsonb NOT NULL DEFAULT '[]'::jsonb,
    languages language[] NOT NULL DEFAULT '{}',
    legendary_actions jsonb NOT NULL DEFAULT '[]'::jsonb,
    melee_attack_actions jsonb NOT NULL DEFAULT '[]'::jsonb,
    ranged_attack_actions jsonb NOT NULL DEFAULT '[]'::jsonb,
    reactions jsonb NOT NULL DEFAULT '[]'::jsonb,
    recharge_actions jsonb NOT NULL DEFAULT '[]'::jsonb,
    regular_actions jsonb NOT NULL DEFAULT '[]'::jsonb,
    saving_throws jsonb NOT NULL DEFAULT '[]'::jsonb,
    skills jsonb NOT NULL DEFAULT '[]'::jsonb,
    speeds jsonb NOT NULL DEFAULT '[]'::jsonb,
    traits jsonb NOT NULL DEFAULT '[]'::jsonb,
    visions jsonb NOT NULL DEFAULT '[]'::jsonb,
    spellcasting jsonb
);

CREATE INDEX IF NOT EXISTS idx_monsters_challenge_rating ON monsters(challenge_rating);
CREATE INDEX IF NOT EXISTS idx_monsters_size ON monsters(size);
CREATE INDEX IF NOT EXISTS idx_monsters_monster_type ON monsters(monster_type);
