export enum Skill {
  Acrobatics = "acrobatics",
  AnimalHandling = "animal_handling",
  Arcana = "arcana",
  Athletics = "athletics",
  Deception = "deception",
  History = "history",
  Insight = "insight",
  Intimidation = "intimidation",
  Investigation = "investigation",
  Medicine = "medicine",
  Nature = "nature",
  Perception = "perception",
  Performance = "performance",
  Persuasion = "persuasion",
  Religion = "religion",
  SleightOfHand = "sleight_of_hand",
  Stealth = "stealth",
  Survival = "survival",
}

export const DisplaySkill: Readonly<Record<Skill, string>> = {
  [Skill.Acrobatics]: "Acrobatics",
  [Skill.AnimalHandling]: "Animal Handling",
  [Skill.Arcana]: "Arcana",
  [Skill.Athletics]: "Athletics",
  [Skill.Deception]: "Deception",
  [Skill.History]: "History",
  [Skill.Insight]: "Insight",
  [Skill.Intimidation]: "Intimidation",
  [Skill.Investigation]: "Investigation",
  [Skill.Medicine]: "Medicine",
  [Skill.Nature]: "Nature",
  [Skill.Perception]: "Perception",
  [Skill.Performance]: "Performance",
  [Skill.Persuasion]: "Persuasion",
  [Skill.Religion]: "Religion",
  [Skill.SleightOfHand]: "Sleight of Hand",
  [Skill.Stealth]: "Stealth",
  [Skill.Survival]: "Survival",
} as const;

export const Skills: Skill[] = Object.values(Skill);
